"""Content provenance — did anything actually READ this element's source?

WHY this exists (2026-08-09, after Eitan looked at the Prompts tab):

The hub already has a `verified` field, and 2,308 elements wear a green "✓ verified" badge.
But that field answers a narrower question than it appears to: it means *the link resolves*,
or *the package installed in a sandbox*. It says nothing about whether the element's
description, use-case and tips are accurate — because for almost everything in the hub, no
model ever read the source.

The bulk analyzer (`src/analyze_batch.py`) works by:
  * `extract_tools_from_text()` — regex-matching 89 HARDCODED tool names, so it is structurally
    blind to any tool nobody typed into that dict by hand; and
  * `extract_tips()` — keeping any sentence that contains the tool's name, is 20-180 chars, and
    contains one of ~11 verbs ("use", "can", "make"...).

That heuristic cannot distinguish a recommendation from a criticism. "Claude can't reliably do
X" contains "claude" and "can", so it lands in the tips list looking like advice.

Only 12 of 3,641 skills carry a `model_version`. So ~99.7% of the hub's *content* was
pattern-matched, while the badge in front of it says "verified".

This module does NOT delete or rewrite anything (P: quarantine, never delete). It adds a
SECOND, honestly-named signal alongside the existing one, so the app can stop implying that a
live link means trustworthy text. Eitan decides what to do about the content afterwards.
"""
from __future__ import annotations

import argparse
import collections
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IDX = ROOT / "data" / "elements_index.json"
SKILLS = ROOT / "data" / "skills.json"
OUT = ROOT / "data" / "content_provenance.json"

# How the element's TEXT was produced — deliberately separate from link/sandbox verification.
MODEL_READ = "model-read"          # a model actually read the source and wrote this
PATTERN = "pattern-matched"        # keyword/regex extraction; nothing comprehended it
AUTHORED = "authored"              # written by a person or by EXCAVA with a model in the loop
UNKNOWN = "unknown"                # cannot tell from the data we keep


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")


def _load(p: Path, default):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return default


def classify_skill(s: dict) -> tuple[str, str]:
    """Return (method, why) for one skill record."""
    if s.get("model_version"):
        return MODEL_READ, f"analyzed by {s['model_version']}"
    if s.get("created_by") == "EXCAVA":
        return AUTHORED, "generated by EXCAVA"
    st = s.get("source_type") or ""
    if st in ("web_news", "youtube", "linked_resource"):
        return PATTERN, (f"{st}: keyword extraction (89-name dict + sentence heuristic), "
                         "no model read the source")
    return UNKNOWN, "no provenance recorded"


def build() -> dict:
    idx = _load(IDX, {})
    els = idx.get("elements") or []
    skills = (_load(SKILLS, {}) or {}).get("skills") or []
    by_slug = {s.get("slug"): s for s in skills if isinstance(s, dict)}
    by_name = {str(s.get("skill_name", "")).lower().strip(): s
               for s in skills if isinstance(s, dict)}

    census = collections.Counter()
    conflicts = 0
    for e in els:
        s = by_slug.get(e.get("id")) or by_name.get(str(e.get("name", "")).lower().strip())
        if s is not None:
            method, why = classify_skill(s)
        elif e.get("created_by") == "EXCAVA":
            method, why = AUTHORED, "generated by EXCAVA"
        else:
            method, why = UNKNOWN, "no provenance recorded"
        e["content_provenance"] = {"method": method, "why": why, "at": _now()}
        census[method] += 1
        # The headline number: elements the UI calls "verified" whose TEXT nothing ever read.
        if (e.get("verified") or {}).get("status") == "verified" and method == PATTERN:
            conflicts += 1
            e["content_provenance"]["conflict"] = (
                "link/sandbox verified, but the description and tips were pattern-matched — "
                "the green badge refers to the link, not to this text")

    idx["elements"] = els
    IDX.write_text(json.dumps(idx, ensure_ascii=False), encoding="utf-8")
    report = {"generated_at": _now(), "total": len(els), "census": dict(census),
              "verified_badge_but_pattern_matched": conflicts,
              "note": "content_provenance answers 'did anything read this?'. The separate "
                      "'verified' field only answers 'does the link resolve / did it install?'."}
    OUT.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--report", action="store_true", help="print the last report without rebuilding")
    a = ap.parse_args()
    r = _load(OUT, None) if a.report else build()
    if not r:
        print("no report yet — run without --report")
        return 1
    print(f"content provenance over {r['total']} elements:")
    for k, v in sorted(r["census"].items(), key=lambda kv: -kv[1]):
        print(f"  {k:16s} {v:6d}  ({100*v/max(r['total'],1):.1f}%)")
    print(f"\n  elements badged 'verified' whose TEXT was only pattern-matched: "
          f"{r['verified_badge_but_pattern_matched']}")
    print("  -> that badge refers to the link resolving, not to the text being accurate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
